### ISSUE TITLE
receive input on change

### ISSUE THREAD

**Issue by ma-gu-16** [krauskopf/node-red-contrib-avr-yamaha#13] opened 2019-05-01 06:41 UTC
Hi, first this node works very well. 

i can confirm for modell RX-V777.

is it possible to get somehow the value if its changed by other devices, like the normal remote. 

i would change the volume slider in my dashboard if someone change it maybe via normal remote. 

ist the avr sending commands, or i have to use the incomming node with an 1-2 second sheduler? so each second the sheduler grab the volume state from the avr ? 

wich is the way to go ? 

thanks in advance.

**Comment by krauskopf** [comment] 2019-05-06 18:57
Happy to hear, that the nodes are working with your model.

The "AVR Yamaha Get" node needs to be triggererd/polled to read settings from your receiver, but the "AVR Yamaha In" node emits a message whenever certain settings are changed in the receiver (e.g. volume). The messages are emitted regardless of why the setting was changed (remote, manual, nodered, ...). 
I think this is what you want.
Have a look at Example 3 in the readme: https://github.com/krauskopf/node-red-contrib-avr-yamaha

**Comment by ma-gu-16** [comment] 2019-05-07 18:46
Ok i tried, seems this doesnt work. 
i already used example 3 , there is no debug in my console. 

i tried to change the volumne and the scene modes with my orginal remote control. 

what else could i try ?

**Comment by krauskopf** [comment] 2019-05-07 18:52
The AVR Yamaha uses UPnP events and does not work on every system . Most of the time, this is because there is already another UPnP service running and blocking port 1900 for other multicast listeners. Also check, that the Topic System.Misc.Event.Notice is written to On.

Where are you running node-red? A raspberry pi? Is there any other software running on the device which might already block the UPnP port?

The other chance that you have is polling for any state changes.

**Comment by ma-gu-16** [comment] 2019-05-07 18:54
its rasberry pi, with redmatic addon. i think someone else is using this port already. is it possible to change the port ?

**Comment by krauskopf** [comment] 2019-05-07 19:02
No, the port 1900 is part of the UPnP standard. Applications which want to access the port have to open the port in REUSE mode. Otherwise, the application is blocking other applications.
Seems like there is already a bugfix for this in homematic: https://homematic-forum.de/forum/viewtopic.php?f=65&t=41452

Maybe upgrade to the newest version, or try to deactivate in homeatic, as stated in the thread.

**Comment by ma-gu-16** [comment] 2019-05-07 19:09
this is 1 year old thread, i have the newest version. 

there is an hint: 

each  UPnP-Announcer should have: SO_REUSEPORT/SO_REUSEADDR

**Comment by krauskopf** [comment] 2019-05-07 19:23
This is what I'm doing. Can you check if the node is working if UPnP is temporary disabled in  /etc/init.d/S50eq3configd as written in the thread? Or maybe homematic is stopped?

**Comment by ma-gu-16** [comment] 2019-05-11 07:53
Hi, i installed nodered fresh by itself on windows 10. installed only your node. 
doesnt work. ip of the receiver is not dynamic. post is 8080. 

could this be a receiver problem ? 

attached a screen, seems it works somehow, but the ip is 0.0.0.0 ist this normal ? 


the above section, there is upnp events received.. but the nodered debug console, shows nothing. 
![flow_avr](https://user-images.githubusercontent.com/22169074/57566948-8f89a600-73d2-11e9-8cd7-04f712f6a001.PNG)

**Comment by krauskopf** [comment] 2019-05-11 18:32
Hi, 

ich wechsel mal auf Deutsch. Das macht es einfacher. Ja das mit 0.0.0.0:1900 passt. 
Auch, dass UPnP Events empfangen werden sieht gut aus. Interessant zu wissen wäre, was empfangen wird.
Leider ist die Ausgabe in der aktuellen Version deaktiviert.
Aber dazu habe ich mal einen Patch angehängt. Kannst Du den bitte mal entpacken und die Datei avr-yamaha.js damit überschreiben. Diese befindet sich unter `<.node-red user Verzeichns>\node_modules\node-red-contrib-avr-yamaha`. Das User Verzeichnis ist i.d.r. unter `C:\user\<username>\.node-red`.
Wird auch beim Starten in der Console angezeigt.

[avr-yamaha.zip](https://github.com/krauskopf/node-red-contrib-avr-yamaha/files/3169357/avr-yamaha.zip)

Danach bitte nochmal das Debug-Log von oben zeigen. Vielen Dank für die Mithilfe!

**Comment by krauskopf** [comment] 2019-05-11 18:39
Noch eine Ergänzung.
Ist 192.168.0.15 die IP des Receivers?

Kannst Du mal folgenden Flow laufen lassen, welcher die Notifications einschaltet:
`[{"id":"459833b0.66c13c","type":"inject","z":"495ff459.b6a00c","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":120,"y":1460,"wires":[["abf83c33.f4f778"]]},{"id":"abf83c33.f4f778","type":"AVR-Yamaha-put","z":"495ff459.b6a00c","device":"9202c38a.6dfd4","name":"","topic":"System.Misc.Event.Notice","payload":"On","x":350,"y":1460,"wires":[["80d8b01.7266fd"]]},{"id":"90c58c85.b19128","type":"debug","z":"495ff459.b6a00c","name":"","active":true,"console":"false","complete":"false","x":570,"y":1520,"wires":[]},{"id":"80d8b01.7266fd","type":"AVR-Yamaha-get","z":"495ff459.b6a00c","device":"9202c38a.6dfd4","name":"","topic":"System.Misc.Event.Notice","x":350,"y":1520,"wires":[["90c58c85.b19128"]]},{"id":"9202c38a.6dfd4","type":"avr-yamaha","z":"495ff459.b6a00c","name":"RX-677","address":"192.168.17.151","port":"8080","debug":true}]`

**Comment by krauskopf** [comment] 2019-05-11 19:56
Ich habe eine neue Version 0.8.5 gepusht. Die enthält auch die erweiterten Debug-Ausgaben. Damit musst du die Datei oben nicht mehr ersetzen. Bitte einfach nur die neuen Console-Ausgaben hier mal ablegen. Danke.

**Comment by krauskopf** [comment] 2021-01-02 18:10
Cannot reproduce and the latest version should have all correct options set. Might be also already fixed in redmatic.

**Closed as completed by krauskopf** 2021-01-02 18:10 UTC
